version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: engsoft_unicamp
      POSTGRES_PASSWORD: 123456789

